version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: ptparchiver
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
      - freebsd
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - 6
    ignore:
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: arm64
      - goos: darwin
        goarch: arm
      - goos: freebsd
        goarch: arm
      - goos: freebsd
        goarch: arm64
    main: ./cmd/ptparchiver/main.go
    binary: ptparchiver

archives:
  - format_overrides:
      - goos: windows
        format: zip
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}

release:
  prerelease: auto
  footer: |
    **Full Changelog**: https://github.com/s0up4200/ptparchiver-go/compare/{{ .PreviousTag }}...{{ .Tag }}

checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_checksums.txt"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch
  groups:
    - title: "New Features"
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: "Bug fixes"
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 10
    - title: Other work
      order: 999

nfpms:
  - package_name: ptparchiver
    maintainer: s0up4200
    description: |-
      ptparchiver is a tool for archiving PTP torrents.
    formats:
      - apk
      - deb
      - rpm
      - archlinux
