services:
  ptparchiver:
    image: ghcr.io/s0up4200/ptparchiver-go:latest
    container_name: ptparchiver
    environment:
      - TZ=UTC
    volumes:
      - ./config:/config
    restart: on-failure:1
    command: run # --interval <minutes> to override config
